### ISSUE TITLE
After seed verified email, can invite friends without having confirmed PayPal 

### ISSUE THREAD

**Issue by olssonresearch** [DukeCityDigital/mysurveys#117]
I registered as a Seed, verified my email. Then I could click friends under home and invite friends. I got the email and could register as a peer. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
@tamaravdd  @olssonresearch 
Hi Tamara and Henrik - I've added new functionality to the front and backend to enforce the sequence of steps in the flowchart below.  Navigation to the next step should be disabled unless they've completed the prerequisite step.  

There's a lot of new code in action, including the database keeping track of who's changed their passwords from the initial value and other changes in behavior based on peers and seeds, and I'm in the process of testing some of it.  There's bound to be some hiccups we need to address - feel free to test the behavior and let me know.  

https://app.diagrams.net/?src=about#G1B225dKftwMrBbQcRtKJemGLtubD08giP
