### ISSUE TITLE
Seeds: if not eligible to participate given questionnaire, next page is blank 

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#119]
After filling out the survey (https://mysurveys.santafe.edu/questionnaire?consent=irb&role=seed), if I am not eligible I just see a blank page. There used to be a page saying I was not eligible. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
Got it - re-added the message that says

 Thank you for your submission. Unfortunately, you aren't a match for any current studies
