### ISSUE TITLE
As a research cannot send invitations even when quota is in place and start date is set to start

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#121]
I get this error "A quota must be in place and the project 'start_state' must be set to 'start' to send invitations" even when I have a quota and the start_state is set to start. @DukeCityDigital

**Comment by olssonresearch** [comment]
I tried this also, works for me until I get the error "One or more users has not verified..", but that is expected as I choose participants that were not verified. However I also got "No Max Payout Is Set For the Project". I set min to 0 and max to 0, and this should be allowed as we might want to do surveys where there are no payouts. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
PL: remove requirements for payouts

**Comment by DukeCityDigital** [comment]
Sorry - misleading error messages - the payout requirements have been removed and this should be fixed !
