### ISSUE TITLE
Seeds get disqualified if they answer "Completely unsafe" on both GM and vaccination, they should be allowed to register

### ISSUE THREAD

**Issue by olssonresearch** [DukeCityDigital/mysurveys#128]
@DukeCityDigital

**Comment by olssonresearch** [comment]
Sorry, mixed up seeds and peers. Seeds should be allowed to register if they answer completely unsafe on both GM and vaccination.

**Comment by DukeCityDigital** [comment]
Ok changes made - just to clarify
**Seeds**
can register if they answer 'completely unsafe' or 'completely' safe to GM or VAC - so they're not being filtered by any of these answers

@olssonresearch
