### ISSUE TITLE
enforce 2 successful peer invitations

### ISSUE THREAD

**Issue by DukeCityDigital** [DukeCityDigital/mysurveys#133]

**Comment by tamaravdd** [comment]
if more people try to sign up, lead them to a page saying "Thank you for your interest, but for now we have enough participants."

This page could be use for friends beyond 2 or even for people after we reach enough participants. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
Added a block to inviting new friends if you already have 2 accepted, and if a friend tries to confirm email for a seed with 2 friends who've already accepted they're shown an error message - see below @tamaravdd  LMK thoughts if necessary
![maxfriends](https://user-images.githubusercontent.com/8813173/109429970-0636cf80-79bc-11eb-8e75-f4342e2afb69.JPG)
![maxfriends2](https://user-images.githubusercontent.com/8813173/109429972-0636cf80-79bc-11eb-970b-b19623d9e602.JPG)
