### ISSUE TITLE
After completing the study, participants should be brought back to the mysurveys tab

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#140]
After completing the study on unipark, participants are brought to an empty dashboard page, they should instead be brought to the mysurveys tab (https://mysurveys.santafe.edu/dashboard/my-projects) to see that they did finish the survey and are waiting on their payment. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
@tamaravdd 
In the UniPark survey configuration we need to change the 'Return URL' to the mysurveys project page - if you can switch it to this we can do a check and make sure
https://mysurveys.santafe.edu/dashboard/my-projects&id=
Currently it is set to:
https://mysurveys.santafe.edu/Return.php&id=
