### ISSUE TITLE
Consent text and questions in different font and size than all the other text

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#142]
In the consent form for both the seed and the peers, the font and size of text is huge and is different than most of the website. Could we make it the same font @DukeCityDigital but keeping the bold sections in bold. 

![image](https://user-images.githubusercontent.com/28162458/108572348-55e80d80-72cf-11eb-9dc1-183152eb7ade.png)

Same for some of the text in the questionnaire, it should be the same font and size throughout. 

![image](https://user-images.githubusercontent.com/28162458/108572523-b2e3c380-72cf-11eb-87c5-f8b283bb6aa8.png)

**Comment by DukeCityDigital** [comment]
removed the font size addition - lmk
