### ISSUE TITLE
For all emails for a project, have support@mysurveys.santafe.edu as the contact adress

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#143]
I tried sending email invites using the default template and no contact information shows up even though in the code I see  *contactaddress*.*nl* *nl*  

![image](https://user-images.githubusercontent.com/28162458/108579818-0103c180-72e6-11eb-8fcc-06b52f80b023.png)

Could we make sure that regardless of the responsible person, the email listed in emails is support@mysurveys.santafe.edu? @DukeCityDigital

**Comment by DukeCityDigital** [comment]
Added text to bottom of invitation emails @tamaravdd 

**For additional project support, contact support@mysurveys.santafe.edu</bold>**
