### ISSUE TITLE
Add question for Peers: "Would it be ok to share your answers to the previous two questions with the friend who invited you to the study?  Yes No""

### ISSUE THREAD

**Issue by olssonresearch** [DukeCityDigital/mysurveys#144]
We realized that we need to add another question for the Peers at the end of the questionnaire with a yes no answer: "Would it be ok to share your answers to the previous two questions with the friend who invited you to the study? 
Yes
No
" 
@DukeCityDigital

**Comment by DukeCityDigital** [comment]
added this function - LMK! @olssonresearch
