### ISSUE TITLE
Email for friends: change text

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#145]
Hi @DukeCityDigital, I am seeing on the php file on mysurveys backend that the language for the emails is the same for researchers and friends with just different wildcards. Could we actually change the text of the friend invite emails only? 

We would like it to be: 

> Hello!
> Your friend is inviting you to join a study that investigates parents’ beliefs about different issues, including vaccination and GM food. 
> 
> The study is completely confidential and you will be paid $10 for signing up and $5 for completing the study.
> 
> Your temporary password..... [etc.] 

Thanks!

**Comment by DukeCityDigital** [comment]
@tamaravdd  the friend verify email is now a different file as requested - it's in the notifications folder and called
FriendVerifyApiEmail

![friendemail](https://user-images.githubusercontent.com/8813173/109500397-75133780-7a53-11eb-9c7b-b7566613bde4.JPG)
