### ISSUE TITLE
Received message that did not qualify after having received message that *did* qualify 

### ISSUE THREAD

**Issue by mcalderon1** [DukeCityDigital/mysurveys#157]
After filling out the screening survey as a peer / friend I was shown a message that I *did* qualify for the study and would be notified when there was a survey available for me to take. However, when I logged in the next day and clicked on the "questionnaires" tab I was shown a message that I wasn't a match for any current studies. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
@mcalderon1  this should be fixed now as well - I ended up adding a database value for whether a user is qualified or not so if there's any issues to iron out we can view them clearly.   There's a note in my email about the 'User tree' that will be useful for checking qualification status - it's on the admin panel (log in as admin) in the first tab at 
https://mysurveys.santafe.edu/dashboard/settings
