### ISSUE TITLE
Paypal accounts being marked as " already in use by another participant"

### ISSUE THREAD

**Issue by mcalderon1** [DukeCityDigital/mysurveys#170]
When trying to input my real Paypal account it kept showing the message that the Paypal account was already in use by another participant despite there not being other participants. Similar issue happened with both seed and peer accounts. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
Maria thanks again - this one was indeed a bug and should be fixed now, feel free to try with random PayPals as you mentioned in the call
