### ISSUE TITLE
Design: paypal page information outside of box 

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#174]
on the PayPal page, the text "If you don't have a PayPal account, you can sign up for one here. Once you have a PayPal account, you can get your PayPal.Me link by clicking here." is within the "Your current info" box which doesn't make sense. Could that text be below "Please enter your Paypal Information below, and click submit"? Thanks @DukeCityDigital! 
<img width="939" alt="mysurveys" src="https://user-images.githubusercontent.com/28162458/113172142-273a4c80-9216-11eb-999e-80b07b8e4e2e.png">

**Comment by tamaravdd** [comment]
Also, the text should add that we need the email address:

So instead of "In order to make payments, we need to have your PayPal.Me link." we need to have "In order to make payments, we need to have your Paypal Email address and PayPal.Me link."

**Comment by DukeCityDigital** [comment]
@tamaravdd  I re-arranged this per the screenshot - lmk!

**Comment by tamaravdd** [comment]
@DukeCityDigital , Could you make the changes I listed on my comment to this issue? Thanks.
