### ISSUE TITLE
Page after peers disqualifies is confusing

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#179]
When peers disqualify for the study, they see this page which has contradictory information. 

![image](https://user-images.githubusercontent.com/28162458/120032360-4efc2580-bfb7-11eb-8b66-d791d4fcec68.png)

@DukeCityDigital could they just see the same page as for seeds, aka only have the part in blue at the bottom (Thank you for answering the questions...)

**Comment by DukeCityDigital** [comment]
@tamaravdd  updated and pushed - lmk!

![change-qualification-message](https://user-images.githubusercontent.com/8813173/120434515-d04a1400-c339-11eb-9f61-1e0c4016bf00.JPG)
