### ISSUE TITLE
Change Text invite friends page

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#180]
@DukeCityDigital see my committed changes on: 
mysurveys/src/app/core/components/friends/friends.component.html

**Comment by DukeCityDigital** [comment]
This is updated - you may have to CTRL+F5 to see the change - it's showing on my end @tamaravdd 

![please-only](https://user-images.githubusercontent.com/8813173/120435310-c96fd100-c33a-11eb-90f0-0c597290802c.JPG)
