### ISSUE TITLE
Cannot add email or link to the emails to participant. 

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#183]
Hi @DukeCityDigital, I am trying out the emails and I cannot seem to be able to ad the contact email and link to the study to the email template. I am attaching the code that I am writing in the email templates section and the email I am receiving. It seems like the toggle *contactaddress* and *link* are not working. 

(To note, there is not an option to add "contactaddress" in the fields for a new project, maybe it could be added or we could use the default email mysurveysteam@gmail.com) 

![image](https://user-images.githubusercontent.com/28162458/120383457-21c6b480-c2e2-11eb-9fe7-859c0d0e66f0.png)

![image](https://user-images.githubusercontent.com/28162458/120383862-a44f7400-c2e2-11eb-8d12-4d42c5aba86b.png)

Thanks!

**Comment by DukeCityDigital** [comment]
@tamaravdd updated and pushed - link appears in email template now
![link-added](https://user-images.githubusercontent.com/8813173/120432193-cd99ef80-c336-11eb-9bc6-f7053966b62a.JPG)
