### ISSUE TITLE
(10) Active email template button

### ISSUE THREAD

**Issue by DukeCityDigital** [DukeCityDigital/mysurveys#200]
10) The buttons for sending emails to individual participants (Manage selected participants tab) only allow for “Send Invitation” or “Remind”. Here it would be good to have the option to send the currently selected custom email to individual participants. Could you please add a button for sending currently active email template.

**Comment by DukeCityDigital** [comment]
@olssonresearch I've added a button as indicated - funny I mentioned this feature earlier today I must have read it.  Let me know if button works as intended - thanks Henrik

**Comment by olssonresearch** [comment]
@DukeCityDigital I couldn't see a new button, but I tried to send with the "invitation" button to individual participants with the custom email panel activated but it still sends the canned project invitation (see screenshot).
![active_email_button](https://user-images.githubusercontent.com/78612710/126131848-8960203c-afcb-46cc-9f61-cd77eae2de7c.jpg)
