### ISSUE TITLE
Researcher panel: participant selection not showing eligible peers or showing ineligible peers

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#66]
In the example project, if the “Eligible Peer (peers with a seed that has verified PayPal Status)” check box is ticked (Under Project Management, Select participants), no eligible peers show up although peers 16 and and 17 seems to be eligible peers.  Also, if  the checkbox for  "Eligible Seed (seeds with at least 1 peer who has verified PayPal)" is ticked, you get seeds 13 and 15. But Participant 13 has 0 verified peers so that participant cannot have a peer with a verified PP id. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
High priority - this fix ix underway and will be included in the Monday 2021-02-01 release

**Comment by DukeCityDigital** [comment]
This bug should be fixed - we were checking if peers had invited friends  😵‍💫
