### ISSUE TITLE
Emails to spam folder

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#67]
Emails still seem to end up in the spam folder, and links in mail don’t work there (e.g., verification email to participants and forgot password mail to researcher). Any progress on trying to get the emails past spam filters? @DukeCityDigital #emails

**Comment by DukeCityDigital** [comment]
I'm working with Nate on this - I've asked him if he can add a certificate to the DNS records for the domain which should eliminate most instances of spam-flagging, and I have a couple smaller measures I'm doing on my end as well.  If we still have mail go to spam, there's another fallback measure we can take (sending the mail directly from the mysurveys domain itself..  

This should be resolved by the Wednesday update - if we still see emails going to spam we'll use our fallback plan - the 'nuclear option'

**Comment by olssonresearch** [comment]
This seems to be better now, at least for my olssonresearch.com emails that are aliases for my gmail account. Both seed and peer emails comes directly to the inbox

**Comment by DukeCityDigital** [comment]
duplicate now
