### ISSUE TITLE
Text for inviting friends to paypal needs to update after 

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#68]
Invite friends to paypal text. The sentence “When they've confirmed their accounts and verified PayPal you'll be eligible to begin”, is displayed even after paypal is verified. Could this disappear and provide the next step? #text #participants

**Comment by DukeCityDigital** [comment]
Yes - will provide a more clear path here.    This fix will be in the Wednesday release - linked to issue #71

**Comment by tamaravdd** [comment]
Now I get a message that my friends are eligible even when I only invited one friend. @DukeCityDigital
