### ISSUE TITLE
Peer’s first time at MySurveys: After the password change need cookies consent and needs to be brought directly to paypal

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#69]
Once a participant has changed the password is changed, it is unclear where to go. The pop up for consenting to cookies does not appear nor does the questionnaire for if parents and beliefs GM food and vaccines (which is the next step) It is under “2. Questionnaire” but that should happen before paypal. @DukeCityDigital  #peers #order

**Comment by DukeCityDigital** [comment]
Underway for Monday 2021-02-01 release, related to #71

**Comment by DukeCityDigital** [comment]
The GDPR flag has been added, and the automatic transition after completing steps has been updated per issue #71 - let me know if this is on track or if we should update the order - thanks @tamaravdd
