### ISSUE TITLE
Consistent order for seeds and peers, seamless transitions, and renaming

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#71]
Seeds: order should first be initial survey, then PayPal, then friends, then my projects
Peers: order should be first profile (to change password), then initial survey (questionnaire), then PayPal., then my projects. 

For the left panel (menu tab), could we remove the numbers and only have "PayPal", "friends" (only for seeds), "my projects" (could we change it to "my surveys"), and "profile".  

If both peers and seeds could be brought to the next step automatically once finished with the previous one that would be a plus.

@DukeCityDigital #order #participants

**Comment by DukeCityDigital** [comment]
Sure thing - this feature is underway and will be included in the Wednesday release

**Comment by DukeCityDigital** [comment]
**The menus have been changed for peers and seeds as requested;**

**re: Consistent order, transitions:**

After completing a step, a window thanks the user and asks them to confirm before moving them to the next step.  The sequence is different for peers as requested.

friend login for testing:
**newfriend@dukecitydigital.com.com
Testpass12!**

**Comment by tamaravdd** [comment]
HI @DukeCityDigital, could we remove the "questionnaire" tab from the left column. This should be done by everyone right away (with those new URLs you created for seeds and peers) and no need to return to it later. Thanks.

**Comment by tamaravdd** [comment]
Related, peers should not see the "friends" button under the "dashboard" section.

**Comment by DukeCityDigital** [comment]
Created issues for these two items, thanks

**Comment by tamaravdd** [comment]
For peers, very smooth transitions! Thank you!

**Comment by tamaravdd** [comment]
For seeds, could they first do paypal then invite friends? @DukeCityDigital

**Comment by tamaravdd** [comment]
Close this as it is a duplicate

**Comment by tamaravdd** [comment]
For peers, we should remove "questionnaire" from the left tab. 

Also, once completing the screener questionnaire, the peer only sees a thank you page but should instead be re-directed to the PayPal page. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
PL:  Check sequence while logged in, and also when logging in after a certain step, redirect to current

**Comment by DukeCityDigital** [comment]
@tamaravdd @olssonresearch these steps should be enforced now according to the diagram (link below).  We have to enforce it if the user goes straight to the next step and also if they log out and come back so that's a couple different tests - let me know what you think!

https://app.diagrams.net/?src=about#G1B225dKftwMrBbQcRtKJemGLtubD08giP
