### ISSUE TITLE
Different screener questionnaires for seeds and peers

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#73]
Would it be at all possible to have a different screener survey (questionnaire) for seeds and invited peers? Maybe based on which linked they followed (either facebook or after receiving an email and changing their passwords). The peer questionnaire page should have a different consent form (IRB) and not include the question about inviting friends. @DukeCityDigital #peers #participants #screener

**Comment by DukeCityDigital** [comment]
Yes of course - this is underway - delivery ETA Wednesday - Is it possible to post a link to the IRB language here @tamaravdd  ? thank you

**Comment by tamaravdd** [comment]
Hi @DukeCityDigital here is the text for seeds and peers: 

[SEEDS] 

**Consent form**

**Purpose of the study:**  You are being asked to participate in a research study that is being done by Mirta Galesic and Henrik Olsson from the Santa Fe Institute, funded by the NSF. The purpose of this study is to investigate parents’ beliefs about different issues, including vaccination and GM food. You are being asked to take part in this study because you are living in the US and are at least 18 years old.
 
This form will explain what to expect when joining the research, as well as the possible risks and benefits of participation. If you have any questions, please ask one of the study researchers.

**What you will do in the study:**  Your participation will involve answering questions about yourself and your opinions, such as “Is growing GM crops is harmful or beneficial to the environment?”, “Are childhood vaccines natural or unnatural?”, and “Do you have children under 18 years of age at home?”. You might be asked to participate in up to three survey waves, each two weeks apart. A survey wave should take no more than 10 minutes. You will also be asked to invite two of your friends, whose opinions are important to you when thinking about parenting, to complete a short questionnaire.
 
**Risks:** There are no known risks in this research, but some individuals may experience discomfort or loss of privacy when answering questions.

**Benefits:** The findings from this project will provide information on belief formation and social influence.
Confidentiality of your information: There are no names or identifying information associated with your responses. Data will be kept securely and not shared with anyone else. Your personal information will only be used for compensation and will not be connected to your answers.

**Payment:** You will receive $5 for each survey wave you participate in and $10 for each friend that completes the study. 

**Right to withdraw from the study:** Your participation in this study is completely voluntary. You have the right to choose not to participate or to withdraw your participation at any point in this study without penalty.  

If you have any questions, concerns, or complaints about the research, please feel free to call Mirta Galesic or Henrik Olsson at (505) 946-2703 or email at support@mysurveys.santafe.edu. If you have questions regarding your rights as a research participant, or about what you should do in case of any harm to you, or if you want to obtain information or offer input, please contact the UNM Office of the IRB (OIRB) at (505) 277-2644 or irb.unm.edu.

[PEERS] 

**Consent form**

**Purpose of the study:**  You are being asked to participate in a research study that is being done by Mirta Galesic and Henrik Olsson from the Santa Fe Institute, funded by the NSF. The purpose of this study is to investigate parents’ beliefs about different issues, including vaccination and GM food. You are being asked to take part in this study because your friend thought you would be interested.
 
This form will explain what to expect when joining the research, as well as the possible risks and benefits of participation. If you have any questions, please ask one of the study researchers.

**What you will do in the study:**  Your participation will involve answering questions about yourself and your opinions, such as “Is growing GM crops is harmful or beneficial to the environment?”, “Are childhood vaccines natural or unnatural?”, and “Do you have children under 18 years of age at home?”. You might be asked to participate in one survey wave. A survey wave should take no more than 10 minutes.
 
**Risks:** There are no known risks in this research, but some individuals may experience discomfort or loss of privacy when answering questions.

**Benefits:** The findings from this project will provide information on belief formation and social influence.
Confidentiality of your information: There are no names or identifying information associated with your responses. Data will be kept securely and not shared with anyone else. Your personal information will only be used for compensation and will not be connected to your answers.

**Payment:** You will receive $10 for signing up for the study and $5 for completing the questionnaire.

**Right to withdraw from the study:** Your participation in this study is completely voluntary. You have the right to choose not to participate or to withdraw your participation at any point in this study without penalty.  

If you have any questions, concerns, or complaints about the research, please feel free to call Mirta Galesic or Henrik Olsson at (505) 946-2703 or email at support@mysurveys.santafe.edu. If you have questions regarding your rights as a research participant, or about what you should do in case of any harm to you, or if you want to obtain information or offer input, please contact the UNM Office of the IRB (OIRB) at (505) 277-2644 or irb.unm.edu.
