### ISSUE TITLE
Screener questionnaire should select participants if they are skeptic of GM OR vaccines

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#77]
In the screener questionnaire, participants should be selected if their choose a value below 6 for the GM OR the vaccines question (not for both he GM AND vaccines question as it currently is) @DukeCityDigital

**Comment by DukeCityDigital** [comment]
Updated - its now acceptable for them to fail one of the questions but not both - LMK if it's working as expected
