### ISSUE TITLE
Add the "Your privacy" popup to the actual first page for participants

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#78]
The privacy popup should appear on the first page seen by participants. For seeds, the screener questionnaire. For peers, the password change page. If we do include the privacy popup, we should remove the "how we will use your data" and "You must also read and agree to the full privacy disclosure" on the IRB/questionnaire page. @DukeCityDigital

**Comment by DukeCityDigital** [comment]
added privacy language to seed version of the questionnaire at the top - 
https://mysurveys.santafe.edu/questionnaire?consent=irb&role=seed

For peers, the privacy policy is below the password change on the dashboard - let me know!

**Comment by tamaravdd** [comment]
@DukeCityDigital The privacy policy did not appear for me as a peer on the password change page.  @olssonresearch did you see the privacy policy when you changed your password as a peer?

**Comment by olssonresearch** [comment]
No, I did see the privacy policy.

**Comment by tamaravdd** [comment]
@olssonresearch, sorry I am confused, you did or you did not?

**Comment by olssonresearch** [comment]
Sorry, too fast. I meant that I did not see the privacy policy. @tamaravdd

**Comment by DukeCityDigital** [comment]
PL:  remove privacy popup item from seeds/peers/  both should be hardcoded above questionnaire
