### ISSUE TITLE
Peer consent form, but Seed questionnaire

### ISSUE THREAD

**Issue by olssonresearch** [DukeCityDigital/mysurveys#88]
If I go directly to mysurveys.santafe.edu in an incognito window, I get the Peer consent form, but I get the Seed questionnaire with the last question being "To complete the study and earn payment you will need to recruit two of your friends to answer questions as well. Is this OK with you?"

**Comment by tamaravdd** [comment]
Maybe the default should be seed.

**Comment by DukeCityDigital** [comment]
Default IRB form should be seed now
