### ISSUE TITLE
For peers after confirming their email they are told to "invite friends" 

### ISSUE THREAD

**Issue by tamaravdd** [DukeCityDigital/mysurveys#91]
It should go directly to changing their passwords then to paypal.  @DukeCityDigital

**Comment by tamaravdd** [comment]
(I originally said "seeds", I meant peers sorry!)

**Comment by olssonresearch** [comment]
For me it worked, I did not get invite friends and got transported to the PayPal page.

**Comment by tamaravdd** [comment]
This was fixed after I emailed Phil.
