### ISSUE TITLE
Cannot complete registration

### ISSUE THREAD

**Issue by olssonresearch** [DukeCityDigital/mysurveys#97]
After going directly to mysurveys.santafe.edu and completing all screener questions there is a line that appears that says:
. "qform { "parents": "true", "gm": "2", "vac": "2", "us": "true", "friends": "" } ---qualified=false', 
and I couldn't continue.

**Comment by DukeCityDigital** [comment]
Bug should be fixed and pushed to server - was a snag with the decision tree on qualifications for seed vs. peer  @olssonresearch
