### ISSUE TITLE
No participants in Example project

### ISSUE THREAD

**Issue by olssonresearch** [DukeCityDigital/mysurveys#98]
I tried the selection in the example project, but 0 users selected no matter the "Include Peers", "Include Seeds settings".

**Comment by DukeCityDigital** [comment]
I reset the database and there's some example participants again - we have a script that populates sample participants - let me know if I should run it @olssonresearch

**Comment by olssonresearch** [comment]
Yes, please run it. Thanks! @DukeCityDigital
